import { MovieContextProvider } from '@/app/(home)/hooks/context'
import './globals.css'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'


const DMSans = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={DMSans.className}>
        <MovieContextProvider>
          {children}
        </MovieContextProvider>
      </body>
    </html>
  )
}
